# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - feature

# Including commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
only_commits:
  files:
    - LiteMessageBus.Extensions.Pusher/
    - LiteMessageBus.Extensions.PusherDemo/

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - '**/bin/*'
    - '**/obj/*'

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

# environment variables
environment:
  global:
    MY_GET_API_KEY:
      secure: 0HqMlO4KT03m1Obda0ta46zbO1EgtiSouotet2O7J7QU5SMEJfrv+GgM0cuNPL9l

    NUGET_API_KEY:
      secure: 6KCShanM7o7Nyq9f85Efr2161/99q2f0xwPEQFMHyXv8OhcqDV85PdCgLV7fWkAq

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

# scripts that run after cloning repository
install:
  # Restore solution packages.
  - dotnet restore LiteMessageBus.Extensions.Pusher.sln

# to run your custom scripts instead of automatic MSBuild
build_script:
  # Build library with debug mode.
  - dotnet pack LiteMessageBus.Extensions.Pusher\LiteMessageBus.Extensions.Pusher.csproj -c Debug

# to disable automatic builds
#build: off

# scripts to run before tests (working directory and environment changes are persisted from the previous steps such as "before_build")
#before_test:
#  - echo script1
#  - ps: Write-Host "script1"

# to run your custom scripts instead of automatic tests
#test_script:
#  - echo This is my custom test script

# scripts to run after tests
#after_test:

# to disable automatic tests
#test: off

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  # pushing all *.nupkg files in build directory recursively
  -   path: '**\LiteMessageBus.Extensions.Pusher.*.nupkg'
      name: Nuget package

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

  # MyGet deployment (feature).
  -   provider: NuGet
      server: https://www.myget.org/F/lite-message-bus
      api_key: $(MY_GET_API_KEY)
      skip_symbols: true
      artifact: Nuget package
      on:
        branch: feature

  # Nuget deployment (master).
  -   provider: NuGet
      api_key: $(NUGET_API_KEY)
      skip_symbols: true
      artifact: Nuget package
      on:
        branch: master

# to disable deployment
#deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - lightalakanzam@gmail.com
    subject: '[LiteMessageBus.Extensions.Pusher] Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

